name: vision
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.18.5
  - opencv
  - pillow>=7.1.2
  - pytorch>=1.7.0
  - pip
  - torchvision>=0.8.1
  - pandas>=1.2.0
  - requests
  - flask
  - pip:
      - openvino-dev>=2024.0.0
      - tensorflow
      - pynput
      - av
      - open3d
      - tqdm
      - opencv-contrib-python
      - datasets
      - nncf
      - filterpy
      - pyttsx3
      - google-generativeai
      - python-dotenv
      - scikit-learn
      - pygame
      - IPython
      - googlemaps